### ISSUE TITLE
Conclusione prova finale?

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/VantaggiAlessio#1]
Nel controllare i vari progetti, ho visto la tua Prova Finale che è ferma da diversi mesi, ma a prima vista sembra che sia completata.
Tuttavia non hai fatto domanda di conclusione sul Portale, in modo che possa valutare e registrare il lavoro.
Mi puoi aggiornare sulla situazione? 
grazie

**Comment by alevantaggi** [comment]
Gentilissimo Professor Corno,
molto probabilmente si tratta di un disguido, dal momento che ho già effettuato la richiesta di conclusione della prova finale, da lei accettata in data 21/09/2023 ed ho così conseguito la laurea triennale in data 05/10/2023.
La ringrazio comunque per la sua comunicazione, cordiali saluti.
Alessio Vantaggi

**Comment by fulcorno** [comment]
Evidentemente ho sbagliato io ad aggiornare qualche elenco.
Correggo subito, scusa per il disturbo
Fulvio
